/**
 * Centralized export of all Mongoose models
 * Use this instead of importing each model individually
 */

export {
  User,
  Address,
  Category,
  Product,
  CategoryAttribute,
  CategoryAttributeValue,
  ProductAttributeValue,
  Cart,
  CartItem,
  Order,
  OrderItem,
  Wishlist,
  Review,
  Notification,
  Otp,
  TempUpdate,
  Coupon,
  StaffProfile,
  AuditLog,
  FeatureFlag,
  AppSetting,
  PaymentLog,
  HomeBanner,
  CustomerTracker,
  POSOrder,
  Subscription,
  Plan,
  RentalBooking,
  // Aliases
  Attribute,
  AttributeValue,
  CompanySettings,
  PasswordReset,
  // Also export types
  type IUser,
  type IAddress,
  type ICategory,
  type IProduct,
  type ICategoryAttribute,
  type ICategoryAttributeValue,
  type IProductAttributeValue,
  type ICart,
  type ICartItem,
  type IOrder,
  type IOrderItem,
  type IPOSOrder,
  type IWishlist,
  type IReview,
  type INotification,
  type IOtp,
  type ITempUpdate,
  type ICoupon,
  type IStaffProfile,
  type IAuditLog,
  type IFeatureFlag,
  type IAppSetting,
  type IPaymentLog,
  type IHomeBanner,
  type ICustomerTracker,
  type ISubscription,
  type SubscriptionStatus,
  type IPlan,
  type IRentalBooking,
  // Also export enums
  RoleEnum,
  FeatureEnum,
  OrderStatusEnum,
  PaymentStatusEnum,
  PaymentMethodEnum,
  NotificationTypeEnum,
  AttributeTypeEnum,
} from "../models/mongoose";
